// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Philosophers.DB.Context;

#nullable disable

namespace Philosophers.DB.Migrations
{
    [DbContext(typeof(SimulationDBContext))]
    partial class SimulationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Philosophers.DB.Entities.DeadlockRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeadlockNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolvedByPhilosopher")
                        .HasColumnType("integer");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SimulationTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.ToTable("DeadlockRecords");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.ForkStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SimulationTime")
                        .HasColumnType("interval");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.ToTable("ForkStateChanges");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.PhilosopherStateChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhilosopherName")
                        .HasColumnType("integer");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SimulationTime")
                        .HasColumnType("interval");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.ToTable("PhilosopherStateChanges");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.SimulationRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RunId"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RunId");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.DeadlockRecord", b =>
                {
                    b.HasOne("Philosophers.DB.Entities.SimulationRun", "SimulationRun")
                        .WithMany("DeadlockRecords")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.ForkStateChange", b =>
                {
                    b.HasOne("Philosophers.DB.Entities.SimulationRun", "SimulationRun")
                        .WithMany("ForkStateChanges")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.PhilosopherStateChange", b =>
                {
                    b.HasOne("Philosophers.DB.Entities.SimulationRun", "SimulationRun")
                        .WithMany("PhilosopherStateChanges")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Philosophers.DB.Entities.SimulationRun", b =>
                {
                    b.Navigation("DeadlockRecords");

                    b.Navigation("ForkStateChanges");

                    b.Navigation("PhilosopherStateChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
